import "server-only";
const MAX_HTML_BYTES = 512_000;
const FETCH_TIMEOUT_MS = 5_000;
export type WebsiteAnalysis = { finalUrl:string; domain:string; hasHttps:boolean; hasBooking:boolean; hasAppointment:boolean; hasContactForm:boolean; hasEcommerce:boolean; hasOnlineOrdering:boolean; hasWhatsApp:boolean; instagramUrl?:string };
function privateHost(hostname:string) { const h=hostname.toLowerCase().replace(/\.$/,""); if(h==="localhost"||h.endsWith(".localhost")||h==="metadata.google.internal") return true; if(/^(127|10)\./.test(h)||/^169\.254\./.test(h)||/^192\.168\./.test(h)) return true; const m=h.match(/^172\.(\d{1,3})\./); if(m&&+m[1]>=16&&+m[1]<=31)return true; return h==="::1"||h.startsWith("fc")||h.startsWith("fd")||h.startsWith("fe80:"); }
export function normalizeWebsiteUrl(value?:string|null):URL|null { if(!value)return null; try {const u=new URL(value); if(!["http:","https:"].includes(u.protocol)||u.username||u.password||u.port||privateHost(u.hostname))return null; return u;}catch{return null;} }
function instagram(html:string) { const values=html.match(/https?:\/\/(?:www\.)?instagram\.com\/[A-Za-z0-9._-]+\/?/gi)??[]; const v=values.find(x=>!/(?:\/p|\/reel|\/reels|\/explore|\/accounts|\/about)(?:\/|$)/i.test(x)); return v?new URL(v).toString():undefined; }
export async function analyzeWebsite(input?:string|null):Promise<WebsiteAnalysis|null> { const initial=normalizeWebsiteUrl(input); if(!initial)return null; let url=initial; let response:Response|undefined; try { for(let i=0;i<=3;i++){const c=new AbortController();const t=setTimeout(()=>c.abort(),FETCH_TIMEOUT_MS);try{response=await fetch(url,{redirect:"manual",signal:c.signal,headers:{Accept:"text/html,application/xhtml+xml"},cache:"no-store"});}finally{clearTimeout(t)} if(response.status>=300&&response.status<400){const location=response.headers.get("location");const next=normalizeWebsiteUrl(location?new URL(location,url).toString():null);if(!next)return null;url=next;continue}break} if(!response?.ok)return null; const type=response.headers.get("content-type")?.toLowerCase()??"";if(type&&!type.includes("text/html")&&!type.includes("application/xhtml+xml"))return null; if(Number(response.headers.get("content-length")??0)>MAX_HTML_BYTES)return null;const bytes=await response.arrayBuffer();if(bytes.byteLength>MAX_HTML_BYTES)return null;const html=new TextDecoder().decode(bytes);const lower=html.toLowerCase(); const hasAppointment=/(appointment|make an appointment|schedule (?:a|your) appointment|cita previa|reservar cita|agendar cita)/i.test(lower); return {finalUrl:url.toString(),domain:url.hostname.toLowerCase(),hasHttps:url.protocol==="https:",hasBooking:/(book(?:ing)?|appointment|reserve|reservas|cita previa|calendly|setmore|fresha|booksy)/i.test(lower),hasAppointment,hasContactForm:/<form\b/i.test(lower)&&/(contact|email|mensaje|message|phone|tel)/i.test(lower),hasEcommerce:/(add to cart|add-to-cart|shopping cart|carrito|woocommerce|shopify|stripe\.com)/i.test(lower),hasOnlineOrdering:/(order online|online ordering|pedido online|deliveroo|glovo|just eat)/i.test(lower),hasWhatsApp:/(?:wa\.me|api\.whatsapp\.com|whatsapp)/i.test(lower),instagramUrl:instagram(html)}; }catch{return null} }

