"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Lead={id:string;businessName:string;businessType:string;location:string;websiteUrl:string|null;googleMapsUrl:string|null;hasWebsite:boolean};
type SearchContext={id:string;businessType:string;location:string;description:string|null;createdAt:string;requestedLeads:number};
function Cards({leads}:{leads:Lead[]}){return <div className="grid gap-4 md:grid-cols-2">{leads.map(lead=><article key={lead.id} className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><h3 className="font-bold">{lead.businessName}</h3><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">New</span></div><p className="mt-2 text-sm text-slate-600">{lead.businessType} · {lead.location}</p><p className="mt-3 text-sm">{lead.hasWebsite?<a className="text-blue-600 hover:underline" href={lead.websiteUrl!} target="_blank" rel="noreferrer">Website</a>:<span className="text-slate-500">No website listed</span>}{lead.googleMapsUrl&&<> · <a className="text-blue-600 hover:underline" href={lead.googleMapsUrl} target="_blank" rel="noreferrer">Google Maps</a></>}</p></article>)}</div>}
export default function LeadsPage(){
 const [businessType,setBusinessType]=useState("Barbershops"),[location,setLocation]=useState("Zaragoza, Spain"),[description,setDescription]=useState(""),[limit,setLimit]=useState("10"),[leads,setLeads]=useState<Lead[]>([]),[search,setSearch]=useState<SearchContext|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[progress,setProgress]=useState("");
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get("searchId");if(!id)return;setLoading(true);setProgress("Loading the saved search…");fetch(`/api/search?searchId=${encodeURIComponent(id)}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Search could not be loaded.");setSearch(d.search);setLeads(d.leads)}).catch(e=>setError(e instanceof Error?e.message:"Search could not be loaded.")).finally(()=>{setLoading(false);setProgress("")})},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError("");setProgress("Preparing your search…");const stages=["Querying Google Places…","Collecting business details…","Saving gathered businesses…"];let stage=0;const timer=window.setInterval(()=>{stage=Math.min(stage+1,stages.length-1);setProgress(stages[stage])},1800);try{const r=await fetch("/api/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({businessType,location,description,limit})});const d=await r.json();if(!r.ok)throw new Error(d.error);setProgress(`Saved ${d.leads.length} businesses.`);setSearch(null);setLeads(d.leads)}catch(e){setError(e instanceof Error?e.message:"Search failed.")}finally{window.clearInterval(timer);setLoading(false)}}
 return <div className="mx-auto max-w-6xl"><header className="mb-8"><p className="text-sm font-medium text-blue-600">Business discovery</p><h1 className="mt-1 text-3xl font-bold tracking-tight">{search?"Gathered businesses":"Find potential clients"}</h1><p className="mt-2 text-slate-600">{search?"Review the businesses gathered in this search.":"Search public business listings with Google Places and save the results locally."}</p></header>
 {search?<section className="mb-8 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-blue-600">Search session</p><h2 className="mt-1 text-xl font-bold">{search.businessType} in {search.location}</h2>{search.description&&<p className="mt-2 text-sm text-slate-600">{search.description}</p>}<p className="mt-2 text-xs text-slate-500">Gathered {new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(search.createdAt))}</p></div><Link href="/dashboard" className="text-sm font-medium text-blue-600 hover:underline">Back to dashboard</Link></div></section>:<section className="rounded-2xl border bg-white p-6 shadow-sm"><form onSubmit={submit} className="grid gap-5 md:grid-cols-2"><label className="text-sm font-semibold">Business type<input className="mt-2 w-full rounded-lg border p-3 font-normal" value={businessType} onChange={e=>setBusinessType(e.target.value)} /></label><label className="text-sm font-semibold">Location<input className="mt-2 w-full rounded-lg border p-3 font-normal" value={location} onChange={e=>setLocation(e.target.value)} /></label><label className="text-sm font-semibold">Number of leads<select className="mt-2 w-full rounded-lg border p-3 font-normal" value={limit} onChange={e=>setLimit(e.target.value)}>{[5,10,20].map(n=><option key={n}>{n}</option>)}</select></label><label className="text-sm font-semibold md:col-span-2">Target description<textarea className="mt-2 min-h-24 w-full rounded-lg border p-3 font-normal" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe the businesses you want to target (optional)" /></label><div className="flex flex-wrap items-center gap-4"><button disabled={loading} className="rounded-lg bg-blue-600 px-5 py-3 font-semibold text-white disabled:opacity-60 md:w-fit">{loading?"Gathering…":"Find leads"}</button>{loading&&<p role="status" aria-live="polite" className="text-sm text-slate-600">{progress}</p>}</div></form></section>}
 {error&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<section className="mt-8"><h2 className="mb-4 text-xl font-bold">{leads.length?`${leads.length} leads found`:"Results"}</h2>{!leads.length&&!loading?<div className="rounded-2xl border border-dashed bg-white p-12 text-center text-slate-500">{search?"This search did not return any businesses.":"Run a search to see businesses here."}</div>:<Cards leads={leads}/>}</section></div>
}

